name: cicd
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt-get update && sudo apt-get -y -qq install clang-tidy cppcheck cflow spell gcc-powerpc64-linux-gnu gcc-aarch64-linux-gnu qemu-user-binfmt
    - name: test-main
      run: make LLVM_VERSION=10
      working-directory: .
    - name: test-multiplatform
      run: make test-multiplatform
      working-directory: .
