name: cicd
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt-get update && sudo apt-get -y -qq install clang-tidy cppcheck cflow spell gcc-powerpc64-linux-gnu gcc-powerpc-linux-gnu gcc-aarch64-linux-gnu gcc-i686-linux-gnu qemu-user-binfmt
    - name: test-main
      run: make LLVM_VERSION=10
      working-directory: .
    - name: test-multiplatform
      run: make test-multiplatform
      working-directory: .
  # Build Windows x86 32 and 64 -bit and run tests
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build Windows target
        run: |
          cmake -G "NMake Makefiles" .
          nmake
          ./buddy_tests
  # Cross-compile Windows x64 -> arm/arm64, doesn't run tests
  cross-compile-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64_arm
          - amd64_arm64
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build Windows target
        run: |
          cmake -G "NMake Makefiles" .
          nmake